services:
  db:
    image: postgres:16
    container_name: mygym-postgres
    environment:
      POSTGRES_DB: mygym
      POSTGRES_USER: mygym
      POSTGRES_PASSWORD: mygym
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: